
PESQUISADOR = 'PESQUISADOR'
PESQUISADO = 'PESQUISADO'

CRIADA = 'CRIADA'
INICIADA = 'INICIADA'
FINALIZADA = 'FINALIZADA'



TIPO_USUARIO = (
    (PESQUISADOR, PESQUISADOR),
    (PESQUISADO, PESQUISADO),
)

STATUS_PESQUISA = (
    (CRIADA, CRIADA),
    (INICIADA, INICIADA),
    (FINALIZADA, FINALIZADA),
)
