# Generated by Django 3.1.3 on 2020-11-16 10:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('CRIADA', 'CRIADA'), ('INICIADA', 'INICIADA'), ('FINALIZADA', 'FINALIZADA')], default='CRIADA', max_length=50, verbose_name='TIPO')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='QuestaoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_pesquisas', to='app_controle_nps.pesquisa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controle_nps.questao', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Questao da Pesquisa',
                'verbose_name_plural': 'Questões da Pesquisa',
                'unique_together': {('pesquisa', 'questao')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(help_text='Nome do Usuário', max_length=255)),
                ('email', models.CharField(help_text='Email, também usulizado como login', max_length=255)),
                ('senha', models.CharField(help_text='Senha do Usuário', max_length=100)),
                ('tipo', models.CharField(choices=[('PESQUISADOR', 'PESQUISADOR'), ('PESQUISADO', 'PESQUISADO')], max_length=50, verbose_name='TIPO')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestaoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('peso', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('questao_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app_controle_nps.questaopesquisa')),
            ],
            options={
                'verbose_name': 'RespostaQuestaoPesquisa',
                'verbose_name_plural': 'RespostaQuestaoPesquisa',
            },
        ),
    ]
