# Generated by Django 3.1.3 on 2020-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0002_auto_20201115_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(choices=[('INICIADA', 'INICIADA'), ('FINALIZADA', 'FINALIZADA')], default=1, max_length=50, verbose_name='TIPO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='peso',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True, verbose_name='Peso'),
        ),
    ]
