# Generated by Django 3.1.3 on 2020-11-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0003_auto_20201115_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(choices=[('CRIADA', 'CRIADA'), ('INICIADA', 'INICIADA'), ('FINALIZADA', 'FINALIZADA')], default='CRIADA', max_length=50, verbose_name='TIPO'),
        ),
    ]
