# Generated by Django 3.1.3 on 2020-11-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0004_auto_20201115_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='peso',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='app_controle_nps.pesquisa'),
        ),
    ]
