# Generated by Django 3.1.3 on 2020-11-16 00:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0006_auto_20201115_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.RemoveField(
            model_name='questao',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='pesquisa',
        ),
        migrations.CreateModel(
            name='QuestaoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Peso')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='app_controle_nps.pesquisa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controle_nps.questao')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
    ]
