# Generated by Django 3.1.3 on 2020-11-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0007_auto_20201116_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='peso',
        ),
    ]
