# Generated by Django 3.1.3 on 2020-11-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0008_remove_questaopesquisa_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaopesquisa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controle_nps.questao', unique=True),
        ),
    ]
