# Generated by Django 3.1.3 on 2020-11-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0009_auto_20201116_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaopesquisa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controle_nps.questao'),
        ),
        migrations.AlterUniqueTogether(
            name='questaopesquisa',
            unique_together={('pesquisa', 'questao')},
        ),
    ]
