# Generated by Django 3.1.3 on 2020-11-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0010_auto_20201116_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaopesquisa',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='app_controle_nps.pesquisa'),
        ),
    ]
