# Generated by Django 3.1.3 on 2020-11-16 00:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0011_auto_20201116_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaopesquisa',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_controle_nps.pesquisa'),
        ),
        migrations.CreateModel(
            name='RespostaQuestaoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('peso', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('questao_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_controle_nps.questaopesquisa')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
    ]
