# Generated by Django 3.1.3 on 2020-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0012_auto_20201116_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questaopesquisa',
            options={'verbose_name': 'QuestaoPesquisa', 'verbose_name_plural': 'QuestaoPesquisa'},
        ),
        migrations.AlterModelOptions(
            name='respostaquestaopesquisa',
            options={'verbose_name': 'RespostaQuestaoPesquisa', 'verbose_name_plural': 'RespostaQuestaoPesquisa'},
        ),
        migrations.RemoveField(
            model_name='respostaquestaopesquisa',
            name='peso',
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respostaquestaopesquisa',
            name='quant_9',
            field=models.IntegerField(default=0),
        ),
    ]
