# Generated by Django 3.1.3 on 2020-11-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0013_auto_20201116_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questaopesquisa',
            name='quant_9',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RespostaQuestaoPesquisa',
        ),
    ]
