# Generated by Django 3.1.3 on 2020-11-16 01:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_nps', '0014_auto_20201116_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_0',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_1',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_10',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_2',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_3',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_4',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_5',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_6',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_7',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_8',
        ),
        migrations.RemoveField(
            model_name='questaopesquisa',
            name='quant_9',
        ),
        migrations.CreateModel(
            name='RespostaQuestaoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('date_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('peso', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('questao_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_controle_nps.questaopesquisa')),
            ],
            options={
                'verbose_name': 'RespostaQuestaoPesquisa',
                'verbose_name_plural': 'RespostaQuestaoPesquisa',
            },
        ),
    ]
